In [37]:
# 1.张量tensor
"""
张量涵盖了一般意义上的标量，向量，矩阵乃至更高维的数据，是进行深度学习的基础，通常与numpy搭配使用
"""
import torch
import numpy as np

# 创建张量（还可使用Tensor函数创建默认为浮点型的张量）
A0 = torch.tensor(1) # 0阶张量（标量）
A1 = torch.tensor([1,2,3]) # 1阶张量（向量）
A2 = torch.tensor([ # 2阶张量（矩阵）
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
A3 = torch.tensor([ # 3阶张量
    [[1,2,3],
     [4,5,6],
     [7,8,9]],

     [[1.1, 2.2, 3.3],
      [4.4, 5.5, 6.6],
      [7.7, 8.8, 9.9]
    ]])
A3.type() # 数据类型，返回'torch.FloatTensor'
A3.shape # 维度信息，返回torch.Size([2, 3, 3])


# 特殊张量的创建
A4 = torch.rand(3,3) # 0-1间的3x3均匀分布数据
A5 = torch.randn(3,3) # 均值为0，方差为1的3x3正态分布数据
"""
还可使用numpy先创建列表，再转换为张量，如下：
A4 = np.random.uniform(size=9).reshape(3,3)
A4 = torch.tensor(A4)
"""
A6 = torch.full([2,3],1) # 2阶（2x3）的值全为1的张量
A7 = torch.arange(0,10,2) # 0到9的，步长为2的1阶张量
A8 = torch.linspace(0,10,steps=4) # 1阶张量，将0-10平均切分为4份
A9 = torch.eyes(3,3) # 3x3单位矩阵

# 张量基本运算
# 切片运算
A = torch.randn(4,4,4)
A[1,[2,3],:3] # 获取第一阶上序号1，第二阶上序号2/3，以及第三阶上序号0/1/2的2x3数据

# 排序
A = torch.tensor([[1,4,3], [4,7,6], [10,9,7]])
torch.sort(A,0,descending=False) # 按张量第一阶升序排序
torch.topk(A,k=2,dim=0,largest=True) # 保留张量第一阶上前两个最大值

# 算术运算
A = torch.randn(4,4,4)
A+3; A-3 # 元素+3/-3
A.pow(2) # 平方
A.pow(0.5) # 开方
torch.exp(A) # 以e为底的指数
torch.log(A) # 以e为底的对数
torch.sum(A) # 所有元素求和，若为torch.sum(A,0)则表示按第一阶对元素求和
torch.mean(A) # 所有元素求均值，若为torch.mean(A,0)则表示按第一阶对元素求均值（仅用于浮点型张量）
torch.max(A) # 所有元素求最大值，其余同上
torch.argmax(A,0) # 沿着张量第一阶返回最大值的索引
torch.min(A) # 所有元素求最小值，其余同上
torch.argmin(A,0) # 沿着张量第一阶返回最小值的索引


# 广播运算
"""
两个张量进行广播运算的基本条件
1.两张量阶数及对应维数相同
2.两张量shape从后往前看，对应阶要么不存在，要么维数是1
"""
A = torch.randn(4,4,4)
B = torch.randn(1,4)
A-B 

# 乘积运算
A = torch.full((2,2,3),4)
B = torch.full((2,2,3),3)
C = torch.full((2,3,2),2)
A*B # 阶数和对应维数相同的张量，对应位置元素相乘
A@C # 张量相乘，最后两阶应遵循矩阵乘法规则

# 张量变换：reshape、squeeze、flatten、cat、stack
# reshape重构张量的阶数和维数，与numpy中reshape功能一致，转换顺序由高阶到低阶，且转换前后元素个数不变
A = torch.randn(2,3,4) # 三阶（2x3x4）
A.reshape(6,4) # 二阶（6x4）
A.reshape(2,12)

# squeeze压缩一个张量可以移除所有长度为1的轴axis，而unsqueeze解压一个张量则会在对应阶数增加一个长度
A = torch.randn(1,12) # 二阶（1x12）
A.squeeze() # 一阶（12）
A.unsqueeze(dim=2) # 三阶（1x12x1）

# flatten可以抹平张量对应阶以后所有阶数，将它完全展平，属于特殊的reshape函数
A = torch.randn(2,3,4) # 三阶（2x3x4）
A.flatten(dim=0) # 一阶（24）：将1阶及以上展平
A.flatten(dim=1) # 二阶（2x12）：将2阶及以上展平

# cat可以按对应阶进行张量拼接
A = torch.randn(2,3)
B = torch.rand(2,3) 
torch.cat((A,B),dim=1) # 二阶（2x6）：按一阶进行拼接，则二阶长度增加

# stack则会增加一个新的阶，并在该阶上对两个张量进行堆叠
A = torch.randn(2,3)
B = torch.rand(2,3)
torch.stack((A,B),dim=1) # 三阶（2x3x2）：按一阶进行堆叠
"""
tensor([[ 0.2775, -0.3184,  1.3068],
        [-0.3685, -0.0498, -1.2364]]) 
 tensor([[0.6206, 0.1927, 0.8001],
        [0.9898, 0.4323, 0.9723]])
tensor([[[ 0.2775,  0.6206],
         [-0.3184,  0.1927],
         [ 1.3068,  0.8001]], r

        [[-0.3685,  0.9898],
         [-0.0498,  0.4323],
         [-1.2364,  0.9723]]])
"""

In [ ]:
# 2.图像PIL与OpenCV
"""
PIL是Python的内置模块，对于一般的图像处理来说已经够用，更专业的则往往要用到OpenCV
"""
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import cv2 as cv

# PIL
# 读入、展示并保存猫猫图片
img = Image.open('path')
img.show()
img.save('path',format=None) # 其中path为保存路径，format（可选）为代转换的图片格式

# 输出类型、格式、尺寸、模式信息
print(type(img), "\n",img,format, "\n",img.size, "\n", img.mode)

# 图片通道分离
r,g,b = img.split() # 以三通道的jpg图像为例，可分割出R,G,B三通道的灰度图像

# 获取图片像素数据矩阵
matrix = np.array(img.getdata(band=None)) # 返回全部通道像素矩阵，其中band=0/1/2分别表示r,g,b单通道

# OpenCV


In [ ]:
# 3.图像处理transform
"""
transform是深度学习torchvision模块下用于图像处理的专用模块，本文介绍它常用的几个函数并作演示
"""
from PIL import Image
from torchvision import transforms

# 打开图片
image = Image.open('C:\\Users\\XGQ\\Desktop\\Programs\\Python\\Python程序\\Learning\\Deep Learning\\Data\\pokeman\\pikachu\\00000000.jpg')
image.show()

# 提取出图片各通道的像素数据，并转换为张量格式
toTensor = transforms.ToTensor()
tensor_img = toTensor(image)
print(tensor_img)

# 将张量数据转为图片
toPILImage = transforms.ToPILImage()
img = toPILImage(tensor_img)
img.show()

# 调整图片大小（原理为图片的上下采样）
resize = transforms.Resize((600,500)) # 调整后高=600, 宽=500
resize_img = resize(img)
resize_img.show()

# 图片标准化
normalize = transforms.Normalize(mean=[0.2,0.2,0.2], std=[0.5,0.5,0.5])
norm_img = toPILImage(normalize(tensor_img))
norm_img.show()

# Compose整合各函数
image = Image.open('C:\\Users\\XGQ\\Desktop\\Programs\\Python\\Python程序\\Learning\\Deep Learning\\Data\\pokeman\\pikachu\\00000000.jpg')
transform = transforms.Compose([
    transforms.resize((600,500)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.2,0.2,0.2], std=[0.5,0.5,0.5])
    ])
img = transform(image)
